// Code generated by "stringer -type Type lexer.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Keyword-0]
	_ = x[Space-1]
	_ = x[Newline-2]
	_ = x[Semicolon-3]
	_ = x[String-4]
	_ = x[Statement-5]
	_ = x[MultiKeyword-6]
	_ = x[Unknown-7]
}

const _Type_name = "KeywordSpaceNewlineSemicolonStringStatementMultiKeywordUnknown"

var _Type_index = [...]uint8{0, 7, 12, 19, 28, 34, 43, 55, 62}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
